# Site settings
title: Jennifer Pouplin
description: Online Research Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jennifer Pouplin
user_description: I am a PhD candidate in Astrodynamics and Space Applications at Purdue University. As part of my dissertation work, I am applying my skills in Planetary Sciences, by modeling the orbital evolution of planetary rings and satellites systems, such as the hypothesized ancient martian ring system, or the contemporary ring system around Chariklo. 
user_title: PhD Candidate at Purdue University, under the supervision of Dr. David A. Minton 
email: jpouplin@purdue.edu
# twitter_username: lorem_ipsum
github_username:  jenniferpouplin
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
