# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://jenniferpouplin.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jennifer Pouplin
user_description: PhD Candidate under the supervision of Dr. David A Minton.
user_title: PhD Candidate under the supervision of Dr. David A Minton
email: jpouplin@purdue.edu
github_username:  jenniferpouplin



exclude: ['package.json', 'src' , 'node_modules']
